apiVersion:  v1
kind:  Service
metadata:  
  name:  my-service
spec:
  type:  LoadBalancer  
  ports:
  - port:  80
    targetPort:  8080
    nodePort:  30005
    protocol:  TCP
  selector:   
    name: kumar
