---
- name: Update and upgrade apt packages
  apt:
   upgrade: yes
   update_cache: yes 
- name: install apache2 on ubuntu
  apt:
   name: apache2
   state: present
- name: copy apache2.conf file
  copy:
   src: apache2.conf
   dest: /etc/apache2
- name: copy html file     
  copy: 
   src: /apps/ansible/index.html
   dest: /var/www/html
  notify: Start_service_httpd
