---
- name: This is my sample playbook
  hosts:  remote
  become_user: yes
  user: root

  vars:
    srce: /apps/ansible/index.html
    desti: /var/www/html
    restart_needed: "{{restart}}"
  tasks:
    - name: Start service httpd, if not started
      service:
        name: apache2
        state: stopped
    - name: Add new user kumar
      user:
        name: kumar
        password: $6$K8vqaAIM$d8PLh3kElNhRH.squgM7As8hpbisIkQS3xoFO7giNFBXpU/dVaoNx.zwH/VB53V8ZzNx0c.oPksREZvOQiV6p1
        comment: kumar
    - name: Copy file with owner and permissions
      copy:
        src: '{{srce}}'
        dest: '{{desti}}'
        owner: kumar
        group: kumar
        mode: '0755'
      notify: restart_apache2
  handlers:
    - name: restart_apache2
      when: restart == "Yes"
      service:
        name: apache2
        state: started
