---
- hosts: prod
  become_user: root
  tasks:
  - name: create a user
    user: 
     name: tibadm
     password: tibadm
  - name: copy a sample file
    copy:
     src: /apps/ansible/sample.txt
     dest: /home/tibadm
